services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project_management_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - app-network

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/1
    networks:
      - app-network

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/1
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
